version: '2'
services:
    soldi-app:
        image: soldi
        external_links:
            - soldi-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/soldi
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    soldi-postgresql:
        extends:
            file: postgresql.yml
            service: soldi-postgresql
